import got from 'got';
import http from 'http';
import createController from './controller';

export default (functions, port) => {
  const server = http.createServer();
  const controller = createController(got, functions);
  const endpoints = functions
    .map(({ method, path }) => ({ method: method.toUpperCase(), path: path.full }));

  server.on('request', controller);

  server.listen(port, () => {
    console.log(`Server is running on port ${port}`);
    console.log('The following endpoints are exposed:');
    console.table(endpoints);
    const cleanUpCommand = `docker rm -f $(docker ps -a -f label=aws-sam-api-proxy.api=${process.env.API_NAME} -q)`;
    console.log(`For removing all containers generated by this script, run the following command - "${cleanUpCommand}"`);
  });
};
